### ISSUE TITLE
Cannot connect to api.php.

### ISSUE THREAD

**Issue by jhernandez26** [IronicBadger/til#6]
Hello, I've downloaded the plugin. I've created the user api as admin and I've added the user authorization in syspass web. 

On the plugin configuration set https://syspassserver , my api token  and my api password (I've set the same password on syspass web for search account and view passwords  in the edit Authorization pop up) how ever the plugin say that I cannot connect to syspass. do you have some idea about this issue.

**Comment by ironicbadger** [comment]
Wrong repo?
